web/config/routes.rb
Rails.application.routes.draw do

  resources :articles do
    resources :comments, only: [:create, :edit, :update, :destroy] do
      resources :replies, only: [:create, :destroy]  
    end

    member do
      post :flag

      # Pinning
      post :pin
      post :unpin
    end  
  end

  resources :companies, path: 'c' do
    resources :comments, only: [:create, :edit, :update, :destroy] do
      resources :replies, only: [:create, :destroy]  
    end


    member do
      post :pin
      post :unpin
    end
  end

  resources :listings do
    resources :comments, only: [:create, :edit, :update, :destroy] do
      resources :replies, only: [:create, :destroy]  
    end

    member do
      post :flag
      post :pin
      post :unpin
    end
  end

  resources :jobs do
    resources :comments, only: [:create, :edit, :update, :destroy] do
      resources :replies, only: [:create, :destroy]  
    end

    member do
      post :flag

      # Pinning
      post :pin
      post :unpin
    end  
  end

  resources :comments, only: [] do  
    resources :replies, only: [:create, :destroy], as: 'replies' do
      member do
        post :flag
      end
    end
    
    member do
      post :flag
    end
  end


  # User Poasts

  resources :poasts do
    resources :comments, only: [:create, :edit, :update, :destroy] do
      resources :replies, only: [:create, :destroy]  
    end

    member do
      post :flag
      post :pin
      delete :unpin
    end
  end

  # Direct Messages
  
  resources :conversations, only: [:index, :new, :show, :create] do
    resources :messages, only: [:create]
  end

  # config/routes.rb
  post 'start_conversation/:recipient_id', to: 'conversations#start_conversation', as: 'start_conversation'



  # Notifications 
  resources :notifications, only: [:index] do
    member do
      post :mark_as_read
    end
    collection do
      post :mark_all_as_read
    end
  end

  # Following/Followers
  resources :relationships, only: [:create, :destroy]


  # Timeline

  get '/timeline', to: 'timelines#show', as: :timeline

  #resources :timelines, only: [:show]

  # Moderator Dashboard
  resources :moderators, only: [:index] do
    collection do
      post :hide_item, as: 'hide_item'
      post :unflag_item, as: 'unflag_item'
      post :lock_user
      post :unlock_user

      # Find and assign/remove badges to users
      post :assign_badge  
      delete :remove_badge 
      get :search_user, as: 'search_user'

      # Create new types of badges
      get :new_badge, as: 'new_badge'
      post :create_badge, as: 'create_badge'

      # Create global alert messages
      get :new_alert
      post :create_alert
      post :remove_alert
    end
  end
  
  # Admin Dashboard
  namespace :admin do
    root to: 'admin#index'  
    resources :advertisers, only: [:index, :new, :create, :edit, :update, :destroy] do
      resources :campaigns, only: [:index, :new, :create, :edit, :update, :destroy] do
        resources :adverts, only: [:index, :new, :create, :edit, :update, :destroy]
      end
    end
  end
  
  # for user IP storage, custom sessions & reg controller
devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
}
  resources :users, only: [:show] do
    resources :poasts, only: [:index]
    
    resources :comments, only: [:create, :edit, :update, :destroy] do
      resources :replies, only: [:create, :destroy]  
    end

    member do
      
      get 'comments'
      get 'listings'
      get 'articles'
      
      get 'edit_bio'
      patch 'update_bio'
      
      post 'flag'
      post 'lock'  

      get 'followers'
      get 'following'

      
    end
  end


  # Search users
  get 'search_users', to: 'users#search'



  # Landing page
  root 'home#index'

  get '/marketplace', to: 'listings#index', as: 'marketplace'
  get '/privacy-policy', to: 'home#privacy_policy'
  get '/terms-of-service', to: 'home#terms_of_service'
  get '/new-user-guide', to: 'home#new_user_guide'
  
  
end

web/app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

web/app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

web/app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

web/app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # Store IP on signup
  def create
    super do |user|
      user.last_ip_address = request.remote_ip
      user.save
    end
  end


  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

web/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  ########################
  # store user IP address
  ########################
  def create
    super do |user|
      user.update(last_ip_address: request.remote_ip)
    end
  end

  #######################


  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

web/app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

web/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :comments, :listings, :articles,
     :edit_bio, :update_bio, :followers, :following]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :edit_bio, :update_bio]

def show
  # may want to eager load badges also, later.
  @user = User.includes(:badges).find_by!(username: params[:id])

  # Adjust the query to include comments count
  @poasts = @user.poasts.where(visible: true)
               .left_joins(:comments)
               .select('poasts.*, COUNT(comments.id) AS comments_count')
               .group('poasts.id')
               .order(created_at: :desc)
               .page(params[:page]).per(5)

  @comments = @user.comments.includes(:replies)
                  .where(visible: true)
                  .order(created_at: :desc)
                  .page(params[:page]).per(10)

rescue ActiveRecord::RecordNotFound
  redirect_to root_path, alert: "User not found"
end



  def old_show 
    # may want to eager load poats and comments also, later. 
    #@user = User.includes(:badges, :poasts, :comments).find_by!(username: params[:id])
    @user = User.includes(:badges).find_by!(username: params[:id])
    @poasts = @user.poasts.where(visible: true).order(created_at: :desc).page(params[:page]).per(5)
    @comments = @user.comments.includes(:replies).where(visible: true).order(created_at: :desc).page(params[:page]).per(10)
  
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path, alert: "User not found"
  end
  
  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "Your profile was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # Edit action_text bio, and avatar      
  def edit_bio
  end

  def update_bio
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_path(@user), notice: 'Bio was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit_bio, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # Flag User Action
  def flag
    return redirect_to @user, alert: "You can't flag yourself." if @user == current_user
    @user.increment!(:flags_count)
    redirect_to @user, notice: 'User has been flagged.'
  end


  # User search
  def search
    @q = User.ransack(params[:q])
  
    if params[:q].present?
      @users = @q.result(distinct: true).page(params[:page]).per(10)
    else # Default users shown, most followers, then the most poasts, then everyone else
      @users = User.all.page(params[:page]).per(10)
      #all_users = User.default_search
      #@users = Kaminari.paginate_array(all_users).page(params[:page]).per(10)
    end
  end
  
  def comments
    @comments = @user.comments.order('created_at DESC').page(params[:page]).per(10) # 10 comments per page
  end
  
  def listings
    @listings = @user.listings.order('created_at DESC').page(params[:page]).per(10) # 10 comments per page
  end
  
  def articles
    @articles = @user.articles.order('created_at DESC').page(params[:page]).per(10) # 10 comments per page
  end


  def followers
    @followers = @user.followers.page(params[:page]).per(10)  # Assuming you're using Kaminari for pagination
  end

  def following
    @following = @user.following.page(params[:page]).per(10)
  end

  
  private

  # Setup for username slugs
  def set_user
    @user = User.find_by!(username: params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path, alert: "User not found"
  end

  # Confirm the correct user.
  def correct_user
    redirect_to(root_url) unless @user == current_user
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:bio, :avatar, :recipient_id)
  end


end
  

web/app/views/users/_article.html.erb
<!-- app/views/users/_article.html.erb -->
<div class="card mb-3">
  <div class="card-body">
    <h5><%= link_to article.title, article_path(article) %></h5>
    <p><%= article.description %></p>
  </div>
</div>

web/app/views/users/_bio_card.html.erb
<!-- _bio_card.html.erb -->
<div class="card mt-4">
  <div class="card-body">
    <div data-controller="show-more">
      <div data-target="show-more.short" class="truncate-text">
        <p class="card-text"><%= bio.to_plain_text.truncate(200) %></p>
      </div>
      <div data-target="show-more.full" class="full-text" style="display:none;">
        <%= bio %>
      </div>
      <button data-target="show-more.button" data-action="click->show-more#toggle" class="btn btn-primary">Show More</button>
    </div>
  </div>
</div>

web/app/views/users/_comment.html.erb
<!-- app/views/users/_comment.html.erb -->
<div class="card mb-3">
  <div class="card-body">
    <%= comment.content %>
    <p class="text-muted mt-2">
      Posted on <%= comment.created_at.strftime('%B %d, %Y') %>
    </p>
  </div>
</div>

web/app/views/users/articles.html.erb
<!-- app/views/users/articles.html.erb -->
<div class="container mt-5">
  <h1 class="mb-4"><%= @user.username %>'s Articles</h1>

  <% if @articles.any? %>
    <div class="list-group">
      <% @articles.each do |article| %>
        <a href="<%= article_path(article) %>" class="list-group-item list-group-item-action">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1"><%= article.title %></h5>
            <small>Published <%= time_ago_in_words(article.created_at) %> ago</small>
          </div>
          <p class="mb-1"><%= truncate(article.description, length: 100) %></p>
          <small>Location: <%= article.location %></small>
        </a>
      <% end %>
    </div>
  <% else %>
    <p>No articles found.</p>
  <% end %>

  <div class="mt-4">
    <%= paginate @articles %>
  </div>
</div>

web/app/views/users/comments.html.erb
<!-- app/views/users/comments.html.erb -->
<h1><%= @user.username %>'s Comments</h1>


<%= render @comments %>

<%= paginate @comments %>

web/app/views/users/edit_bio.html.erb
<!-- app/views/users/edit_bio.html.erb -->
<div class="container mt-5">
  <h1>Edit Bio</h1>

  <!-- Display Errors -->
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(@user.errors.count, "error") %> prohibited this update:</h4>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: @user, url: update_bio_user_path(@user), method: :patch, local: true) do |form| %>
    <div class="form-group">
      <%= form.label :bio %>
      <%= form.rich_text_area :bio, class: "form-control" %>

      <hr class="mt-4">

      <%= form.label :avatar %>
      <%= form.file_field :avatar %>
    </div>
    <%= form.submit 'Update Bio', class: 'btn btn-primary mt-4' %>
  <% end %>
</div>

web/app/views/users/followers.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-12">
      <h1 class="mb-4"><%= @user.username %>'s Followers</h1>

      <% if @followers.any? %>
        <!-- Pagination Controls (Top) -->
        <div class="mb-3">
          <%= paginate @followers %>
        </div>

        <div class="list-group">
          <% @followers.each do |follower| %>
            <div class="list-group-item list-group-item-action d-flex align-items-center justify-content-between">
              <a href="<%= user_path(follower) %>" class="d-flex align-items-center">
                <%= render partial: 'shared/avatar', locals: { user: follower } %>
                <span style="margin-left: 1rem;"><%= follower.username %></span>
              </a>
              <div>
                <span class="d-inline-block mr-2">
                  <%= render partial: 'shared/follow_button', locals: { user: follower } %>
                </span>
                <span class="d-inline-block">
                  <%= render partial: 'shared/send_message_button', locals: { user: follower } %>
                </span>
              </div>
            </div>
          <% end %>
        </div>

        <!-- Pagination Controls (Bottom) -->
        <div class="mt-3">
          <%= paginate @followers %>
        </div>

      <% else %>
        <p class="text-muted">No followers at the moment.</p>
      <% end %>
    </div>
  </div>
</div>

web/app/views/users/following.html.erb
<div class="container mt-5">
  <div class="row">
    <!-- Main Content - User's Following List -->
    <div class="col-md-8">
      <h1 class="mb-4"><%= @user.username %>'s Following</h1>

      <!-- Pagination Controls (Top) -->
      <div class="mb-3">
        <%= paginate @following %>
      </div>

      <div class="list-group">
        <% @following.each do |followed_user| %>
          <div class="list-group-item list-group-item-action d-flex align-items-center justify-content-between">
            <a href="<%= user_path(followed_user) %>" class="d-flex align-items-center">
              <%= render partial: 'shared/avatar', locals: { user: followed_user } %>
              <span style="margin-left: 1rem;"><%= followed_user.username %></span>
            </a>
            <div>
              <span class="d-inline-block mr-2">
                <%= render partial: 'shared/follow_button', locals: { user: followed_user } %>
              </span>
              <span class="d-inline-block">
                <%= render partial: 'shared/send_message_button', locals: { user: followed_user } %>
              </span>
            </div>
          </div>
        <% end %>
      </div>

      <!-- Pagination Controls (Bottom) -->
      <div class="mt-3">
        <%= paginate @following %>
      </div>
    </div>

    <!-- Who to Follow Section -->
    <div class="col-md-4 mt-4">
      <h3>Who to Follow</h3>
      <div class="list-group">
        <% User.who_to_follow(current_user).each do |suggest_user| %>
          <div class="list-group-item d-flex justify-content-between align-items-center">
            <div class="d-flex align-items-center">
              <%= render partial: 'shared/avatar', locals: { user: suggest_user } %>
              <%= link_to suggest_user.username, user_path(suggest_user), class: "ml-2", style: "margin-left: 1rem;" %>
            </div>
            <%= render partial: 'shared/follow_button', locals: { user: suggest_user } %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

web/app/views/users/listings.html.erb
<!-- app/views/users/listings.html.erb -->
<div class="container mt-5">
  <h1 class="mb-4"><%= @user.username %>'s Listings</h1>

  <% if @listings.any? %>
    <div class="list-group">
      <% @listings.each do |listing| %>
        <a href="<%= listing_path(listing) %>" class="list-group-item list-group-item-action">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1"><%= listing.title %></h5>
            <small>Posted <%= time_ago_in_words(listing.created_at) %> ago</small>
          </div>
          <p class="mb-1"><%= truncate(listing.description, length: 100) %></p>
          <small>Price: <%= number_to_currency(listing.price) %></small>
        </a>
      <% end %>
    </div>
  <% else %>
    <p>No listings found.</p>
  <% end %>

  <div class="mt-4">
    <%= paginate @listings %>
  </div>
</div>

web/app/views/users/notifications.html.erb
<h1>Your Notifications</h1>

<ul>
  <% @notifications.each do |notification| %>
    <!-- Add a unique ID for the list item -->
    <li id="notification_<%= notification.id %>">
      <% notifiable = notification.notifiable %>
      <% case notifiable.class.name %>
      <% when 'Comment' %>
        <%= link_to notification.message, polymorphic_path(notifiable.commentable, anchor: "comment_#{notifiable.id}") %>
      <% when 'Reply' %>
        <% comment = notifiable.comment %>
        <% commentable = comment.commentable %>
        <%= link_to notification.message, polymorphic_path(commentable, anchor: "reply_#{notifiable.id}") %>
      <% else %>
        <!-- Fallback content for notifiables without a commentable -->
        <%= notification.message %>
      <% end %>
      <!-- Modify form_with to include data-turbo-frame -->
      <%= form_with url: mark_as_read_notification_path(notification), method: :post, data: { turbo_frame: "notification_#{notification.id}" } do %>
        <%= submit_tag 'Mark as Read', class: 'btn btn-sm btn-primary' %>
      <% end %>
      <small>Received at <%= notification.created_at.strftime('%Y-%m-%d %H:%M:%S') %></small>
    </li>
  <% end %>
</ul>

web/app/views/users/search.html.erb
      <% content_for :page_title do %>
        Search Users
      <% end %>

<div class="container mt-5">
  <div class="d-flex justify-content-center mb-5">
    <%= render 'shared/user_search' %>
  </div>

  <div class="row">
    <% @users.each do |user| %>
      <%= render 'shared/user_card', user: user %>
    <% end %>
  </div>

  <div class="mt-4">
    <%= paginate @users %>
  </div>
</div>

web/app/views/users/show.html.erb
<div class="container mt-5 mb-5">
  <div class="row">
    <div class="col-md-12"><div class="d-flex align-items-center">
  <h1 class="mb-0 mr-3 lobster-font" style="margin-right: 1rem;"><%= @user.username.capitalize %>'s Profile</h1>
  <div class="me-2">
    <%= render 'shared/send_message_button', user: @user %>
  </div>
  <div>
    <%= render 'shared/follow_button', user: @user %>
  </div>
</div>

    <div class="mt-2">
      <%= render partial: 'shared/avatar', locals: { user: @user } %>

      <%= link_to pluralize(@user.followers.count, 'Follower'), followers_user_path(@user) %>

      <%= link_to @user.following.count.to_s +  ' Following', following_user_path(@user) %>
    </div>

    <div class="row">
      <div class="col-md-12">
      <% @user.badges.each do |badge| %>
        <div class="badge">
          <% if badge.image.attached? %>
            <%= image_tag badge.image.variant(:thumb), width: '50', height: '50', class: 'img-thumbnail mb-3' %>
          <% end %>
        </div>
       <% end %>
       </div>
    </div>

      <!-- User Actions -->
     <div class="mt-4 mb-3">
  <% if current_user == @user %>
    <%= link_to edit_user_registration_path, class: 'btn btn-warning' do %>
      <i class="fa fa-lock"></i> Change Password
    <% end %>
    <%= link_to edit_bio_user_path(@user), class: 'btn btn-primary' do %>
      <i class="fa fa-pencil-alt"></i> Edit Bio
    <% end %>
  <% end %>
</div>

<!-- Moderator Actions -->
<% if current_user&.moderator? %>
  <%= button_to lock_user_path(@user), method: :post, class: 'btn btn-danger mt-2' do %>
    <i class="fa fa-user-lock"></i> Lock User
  <% end %>
<% end %>

<!-- Flag User -->
<% unless current_user == @user %>
  <%= button_to flag_user_path(@user), method: :post, class: 'btn btn-warning mt-2' do %>
    <i class="fa fa-flag"></i> Flag User
  <% end %>
<% end %>

      <!-- Bio -->

      <% if @user.bio.present? %>
            <h2 class="mt-4 lobster-font">Bio</h2>
        <%= render partial: 'bio_card', locals: { bio: @user.bio } %>

      <% end %>

      

      <!-- Poasts -->
  <h2 class="mt-5 lobster-font">Poasts</h2>
  <% if user_signed_in? && current_user == @user %>
    <%= link_to 'Create New Poast', new_poast_path, class: "btn btn-primary mb-4", role: "button" %>
  <% end %>

  <div class="row">
    <% if @poasts.any? %>
      <% @poasts.each do |poast| %>
        <!-- Adjust the column size here -->
        <div class="col-md-4 col-sm-6">
          <%= render 'shared/poast_card', poast: poast %>
        </div>
      <% end %>
      <!-- Pagination -->
      <div class="mt-3 col-12">
        <%= paginate @poasts %>
      </div>
    <% else %>
      <p class="text-muted">Nothing here yet. Stay tuned!</p>
    <% end %>
  </div>

      <!-- Comments -->
      <%= render partial: 'shared/comments_section', locals: { comments: @comments, commentable: @user } %>

      <!-- User Activity -->
      <h2 class="mt-4 lobster-font">Activity</h2>
      <ul class="list-group">
        <li class="list-group-item"><%= link_to "View Comment History", comments_user_path(@user) %></li>
        <li class="list-group-item"><%= link_to "View Listings", listings_user_path(@user) %></li>
        <li class="list-group-item"><%= link_to "View Articles", articles_user_path(@user) %></li>
      </ul>

      <!-- Badges -->




    </div> <!-- col-md-12 -->
  </div> <!-- row -->
</div> <!-- container -->