web/config/routes.rb
Rails.application.routes.draw do

  resources :articles do
    resources :comments, only: [:create, :edit, :update, :destroy] do
      resources :replies, only: [:create, :destroy]  
    end

    member do
      post :flag

      # Pinning
      post :pin
      post :unpin
    end  
  end

  resources :companies, path: 'c' do
    resources :comments, only: [:create, :edit, :update, :destroy] do
      resources :replies, only: [:create, :destroy]  
    end


    member do
      post :pin
      post :unpin
    end
  end

  resources :listings do
    resources :comments, only: [:create, :edit, :update, :destroy] do
      resources :replies, only: [:create, :destroy]  
    end

    member do
      post :flag
      post :pin
      post :unpin
    end
  end

  resources :jobs do
    resources :comments, only: [:create, :edit, :update, :destroy] do
      resources :replies, only: [:create, :destroy]  
    end

    member do
      post :flag

      # Pinning
      post :pin
      post :unpin
    end  
  end

  resources :comments, only: [] do  
    resources :replies, only: [:create, :destroy], as: 'replies' do
      member do
        post :flag
      end
    end
    
    member do
      post :flag
    end
  end


  # User Poasts

  resources :poasts do
    resources :comments, only: [:create, :edit, :update, :destroy] do
      resources :replies, only: [:create, :destroy]  
    end

    member do
      post :flag
      post :pin
      delete :unpin
    end
  end

  # Direct Messages
  
  resources :conversations, only: [:index, :new, :show, :create] do
    resources :messages, only: [:create]
  end

  # config/routes.rb
  post 'start_conversation/:recipient_id', to: 'conversations#start_conversation', as: 'start_conversation'



  # Notifications 
  resources :notifications, only: [:index] do
    member do
      post :mark_as_read
    end
    collection do
      post :mark_all_as_read
    end
  end

  # Following/Followers
  resources :relationships, only: [:create, :destroy]


  # Timeline

  get '/timeline', to: 'timelines#show', as: :timeline

  #resources :timelines, only: [:show]

  # Moderator Dashboard
  resources :moderators, only: [:index] do
    collection do
      post :hide_item, as: 'hide_item'
      post :unflag_item, as: 'unflag_item'
      post :lock_user
      post :unlock_user

      # Find and assign/remove badges to users
      post :assign_badge  
      delete :remove_badge 
      get :search_user, as: 'search_user'

      # Create new types of badges
      get :new_badge, as: 'new_badge'
      post :create_badge, as: 'create_badge'

      # Create global alert messages
      get :new_alert
      post :create_alert
      post :remove_alert
    end
  end
  
  # Admin Dashboard
  namespace :admin do
    root to: 'admin#index'  
    resources :advertisers, only: [:index, :new, :create, :edit, :update, :destroy] do
      resources :campaigns, only: [:index, :new, :create, :edit, :update, :destroy] do
        resources :adverts, only: [:index, :new, :create, :edit, :update, :destroy]
      end
    end
  end
  
  # for user IP storage, custom sessions & reg controller
devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
}
  resources :users, only: [:show] do
    resources :poasts, only: [:index]
    
    resources :comments, only: [:create, :edit, :update, :destroy] do
      resources :replies, only: [:create, :destroy]  
    end

    member do
      
      get 'comments'
      get 'listings'
      get 'articles'
      
      get 'edit_bio'
      patch 'update_bio'
      
      post 'flag'
      post 'lock'  

      get 'followers'
      get 'following'

      
    end
  end


  # Search users
  get 'search_users', to: 'users#search'



  # Landing page
  root 'home#index'

  get '/marketplace', to: 'listings#index', as: 'marketplace'
  get '/privacy-policy', to: 'home#privacy_policy'
  get '/terms-of-service', to: 'home#terms_of_service'
  get '/new-user-guide', to: 'home#new_user_guide'
  
  
end

web/app/views/shared/_action_buttons.html.erb
<% allowed_resources = ['listing', 'company', 'job', 'article', 'poast'] %>
<% if allowed_resources.include?(resource_type) %>
  <%= form_with url: send("flag_#{resource_type}_path", resource), method: :post, class: 'd-inline-block me-1' do %>
    <%= button_tag type: 'submit', class: 'btn btn-warning' do %>
      <i class="fa fa-flag"></i> 
    <% end %>
  <% end %>

  <% if current_user && (resource.user == current_user || current_user.moderator?) %>
    <%= link_to send("edit_#{resource_type}_path", resource), class: 'btn btn-primary me-1' do %>
      <i class="fa fa-edit"></i>
    <% end %>
    <%= form_with model: resource, method: :delete, local: true, class: 'd-inline me-1' do |form| %>
      <%= button_tag(type: 'submit', class: 'btn btn-danger', data: { confirm: 'Are you sure?' }) do %>
        <i class="fas fa-trash"></i>
      <% end %>
    <% end %>
  <% end %>

  <%= link_to send("#{resource_type.pluralize}_path"), class: 'btn btn-secondary me-1' do %>
    <i class="fa fa-arrow-left"></i> 
  <% end %>
<% end %>

web/app/views/shared/_avatar.html.erb
<% if user.avatar.attached? %>
  <%= image_tag user.avatar, alt: "User's avatar", width: 65, height: 65, class: "rounded-circle" %>
<% else %>
  <!-- Fallback avatar if user doesn't have one -->
  <div class="rounded-circle shadow-1-strong" style="width: 65px; height: 65px; background-color: grey;"></div>
<% end %>

web/app/views/shared/_comments_section.html.erb
<!-- _comments_section.html.erb -->
<h2 class="mt-5 lobster-font">Comments!</h2>

<div class="row mt-2">
  <div class="col">
    <% comments.each do |comment| %>
      <%= render partial: 'comments/comment', locals: { comment: comment } %>
    <% end %>
  </div>
</div>

<div class="mt-4">
  <%= paginate comments %>
</div>


<div class="row mt-2">
  <div class="col">
    <% if user_signed_in? %>
      <%= render 'comments/form', commentable: commentable %>
    <% else %>
      <p>You must be logged in to post a comment.</p>
    <% end %>
  </div>
</div>

web/app/views/shared/_follow_button.html.erb
<% if current_user %>
  <% unless current_user == user %>
    <div id="follow_form">
      <% if current_user.following?(user) %>
        <%= form_with(url: relationship_path(current_user.active_relationships.find_by(followed_id: user.id)), method: :delete) do |f| %>
          <%= f.button type: 'submit', class: 'btn-as-link' do %>
            <i class="fas fa-user-minus text-danger fa-2x"></i> 
          <% end %>
        <% end %>
      <% else %>
        <%= form_with(url: relationships_path, method: :post) do |f| %>
          <%= f.hidden_field :followed_id, value: user.id %>
          <%= f.button type: 'submit', class: 'btn-as-link' do %>
            <i class="fas fa-user-plus text-primary fa-2x"></i> 
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>

web/app/views/shared/_poast_card.html.erb
<!-- app/views/shared/_poast_card.html.erb -->

<div class="col">
  <%= link_to poast_path(poast), class: "no-underline" do %>
    <div class="card mb-3 custom-poast-card">
      <% if poast.thumbnail.attached? %>
        <% begin %>
          <%= image_tag poast.thumbnail.variant(resize_to_limit: [350, 300]), class: 'card-img-top' %>
        <% rescue ActiveStorage::InvariableError %>
          <%= image_tag 'default-thumbnail.webp', class: 'card-img-top' %>
        <% end %>
      <% end %>
      <div class="card-body">
        <h5 class="card-title"><%= poast.title %></h5>
        <p class="card-text"><%= poast.subheading %></p>
        
        <!-- Avatar and Posted by -->
        <div class="d-flex align-items-center mt-3">
          <div class="me-3">
            <%= render partial: 'shared/avatar', locals: { user: poast.user } %>
          </div>
          <div>
            Posted by: <%= link_to poast.user.username.capitalize, user_path(poast.user) %>
            <span class="text-muted small">- <%= time_ago_in_words(poast.created_at) %> ago</span>
          </div>
        </div>

        <!-- Views -->
        <div class="mt-3">
          <small class="text-muted">
            <i class="fas fa-eye" style="margin-right: 5px;"></i> <%= poast.views %> views
          </small>
          <small class="text-muted" style="margin-left: 15px;"> <!-- Adjusted inline margin-left for spacing -->
            <i class="fas fa-comments" style="margin-right: 5px;"></i> <%= pluralize(poast.comments_count, 'comment') %>
          </small>
        </div>
      </div>
    </div>
  <% end %>
</div>

web/app/views/shared/_send_message_button.html.erb
<% if current_user && user != current_user %>
  <%= form_with(url: start_conversation_path(user.id), method: :post) do |f| %>
    <%= f.button type: 'submit', class: 'btn-as-link' do %>
      <i class="fas fa-comment-dots fa-2x"></i>
    <% end %>
  <% end %>
<% end %>

web/app/views/shared/_start_conversation.html.erb
<% unless @user == current_user %>
    <%= form_with url: start_conversation_user_path(@user), method: :post do %>
    <%= submit_tag "Start a Conversation", class: "btn btn-primary" %>
    <% end %>
<% end %>

web/app/views/shared/_user_card.html.erb
<!-- app/views/shared/_user_card.html.erb -->
<div class="col-md-4 mb-4">
  <div class="card">
    <div class="card-top">
      <div class="avatar-container" style="margin-left: 1.25rem; margin-top: 1.25rem;">
        <%= render 'shared/avatar', user: user %>
      </div>
      <div class="card-icons" style="margin-right: 1.25rem; margin-top: 1.25rem;">
        <%= render 'shared/send_message_button', user: user %>
        <%= render 'shared/follow_button', user: user %>
      </div>
    </div>
    <div class="card-body">
    <div class="card-body">
  <div class="d-flex justify-content-between align-items-center">
    <h5 class="card-title mb-0">
      <%= link_to user.username.capitalize, user_path(user) %>
    </h5>
    <small class="text-muted">
      <%= pluralize(user.followers.count, 'follower') %>
    </small>
  </div>
  <p class="card-text mt-2">
    <%= truncate(user.bio.to_plain_text, length: 80) %>
  </p>
</div>

    </div>
  </div>
</div>

web/app/views/shared/_user_search.html.erb
<div class="card rounded">
  <div class="card-body">
    <%= search_form_for @q, url: search_users_path, html: { class: 'form-inline' } do |f| %>

      <div class="form-group mb-2">
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text custom-icon">
              <i class="fa fa-search"></i>
            </span>
          </div>
          <%= f.search_field :username_or_email_cont, placeholder: 'Username or email', class: 'form-control' %>
        </div>
      </div>

      <button type="submit" class="btn btn-primary mt-2 mb-2">
        <i class="fa fa-search"></i> Search
      </button>

    <% end %>
  </div>
</div>