web/config/routes.rb
Rails.application.routes.draw do

  resources :articles do
    resources :comments, only: [:create, :edit, :update, :destroy] do
      resources :replies, only: [:create, :destroy]  
    end

    member do
      post :flag

      # Pinning
      post :pin
      post :unpin
    end  
  end

  resources :companies, path: 'c' do
    resources :comments, only: [:create, :edit, :update, :destroy] do
      resources :replies, only: [:create, :destroy]  
    end


    member do
      post :pin
      post :unpin
    end
  end

  resources :listings do
    resources :comments, only: [:create, :edit, :update, :destroy] do
      resources :replies, only: [:create, :destroy]  
    end

    member do
      post :flag
      post :pin
      post :unpin
    end
  end

  resources :jobs do
    resources :comments, only: [:create, :edit, :update, :destroy] do
      resources :replies, only: [:create, :destroy]  
    end

    member do
      post :flag

      # Pinning
      post :pin
      post :unpin
    end  
  end

  resources :comments, only: [] do  
    resources :replies, only: [:create, :destroy], as: 'replies' do
      member do
        post :flag
      end
    end
    
    member do
      post :flag
    end
  end


  # User Poasts

  resources :poasts do
    resources :comments, only: [:create, :edit, :update, :destroy] do
      resources :replies, only: [:create, :destroy]  
    end

    member do
      post :flag
      post :pin
      delete :unpin
    end
  end

  # Direct Messages
  
  resources :conversations, only: [:index, :new, :show, :create] do
    resources :messages, only: [:create]
  end

  # config/routes.rb
  post 'start_conversation/:recipient_id', to: 'conversations#start_conversation', as: 'start_conversation'



  # Notifications 
  resources :notifications, only: [:index] do
    member do
      post :mark_as_read
    end
    collection do
      post :mark_all_as_read
    end
  end

  # Following/Followers
  resources :relationships, only: [:create, :destroy]


  # Timeline

  get '/timeline', to: 'timelines#show', as: :timeline

  #resources :timelines, only: [:show]

  # Moderator Dashboard
  resources :moderators, only: [:index] do
    collection do
      post :hide_item, as: 'hide_item'
      post :unflag_item, as: 'unflag_item'
      post :lock_user
      post :unlock_user

      # Find and assign/remove badges to users
      post :assign_badge  
      delete :remove_badge 
      get :search_user, as: 'search_user'

      # Create new types of badges
      get :new_badge, as: 'new_badge'
      post :create_badge, as: 'create_badge'

      # Create global alert messages
      get :new_alert
      post :create_alert
      post :remove_alert
    end
  end
  
  # Admin Dashboard
  namespace :admin do
    root to: 'admin#index'  
    resources :advertisers, only: [:index, :new, :create, :edit, :update, :destroy] do
      resources :campaigns, only: [:index, :new, :create, :edit, :update, :destroy] do
        resources :adverts, only: [:index, :new, :create, :edit, :update, :destroy]
      end
    end
  end
  
  # for user IP storage, custom sessions & reg controller
devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
}
  resources :users, only: [:show] do
    resources :poasts, only: [:index]
    
    resources :comments, only: [:create, :edit, :update, :destroy] do
      resources :replies, only: [:create, :destroy]  
    end

    member do
      
      get 'comments'
      get 'listings'
      get 'articles'
      
      get 'edit_bio'
      patch 'update_bio'
      
      post 'flag'
      post 'lock'  

      get 'followers'
      get 'following'

      
    end
  end


  # Search users
  get 'search_users', to: 'users#search'



  # Landing page
  root 'home#index'

  get '/marketplace', to: 'listings#index', as: 'marketplace'
  get '/privacy-policy', to: 'home#privacy_policy'
  get '/terms-of-service', to: 'home#terms_of_service'
  get '/new-user-guide', to: 'home#new_user_guide'
  
  
end

web/app/models/campaign.rb
class Campaign < ApplicationRecord
    belongs_to :advertiser
    has_many :adverts, dependent: :destroy
  
    enum status: { inactive: 0, active: 1, completed: 2 }
end
  

web/app/controllers/admin/campaigns_controller.rb
class Admin::CampaignsController < ApplicationController
  before_action :authenticate_admin!
  before_action :authenticate_user!
  before_action :find_advertiser
  before_action :find_campaign, only: [:edit, :update, :destroy]

  def index
    @campaigns = @advertiser.campaigns.includes(:advertiser)
  end

  def new
    @campaign = @advertiser.campaigns.build
  end

  def create
    @campaign = @advertiser.campaigns.build(campaign_params)
    if @campaign.save
      redirect_to admin_advertiser_campaigns_path(@advertiser), notice: 'Campaign successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @campaign.update(campaign_params)
      redirect_to admin_advertiser_campaigns_path(@advertiser), notice: 'Campaign successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @campaign.destroy
    redirect_to admin_advertiser_campaigns_path(@advertiser), notice: 'Campaign successfully deleted.'
  end

  private

  def authenticate_admin!
    unless current_user&.administrator?
      redirect_to root_path, alert: "You are not authorized to access this page."
    end
  end

  def find_advertiser
    @advertiser = Advertiser.find(params[:advertiser_id])
  end

  def find_campaign
    @campaign = @advertiser.campaigns.find(params[:id])
  end

  def campaign_params
    params.require(:campaign).permit(:name, :description, :budget, :start_date, :end_date, :status, :advertiser_id)
  end
end

web/app/views/admin/campaigns/_campaign_form.html.erb
<%= form_for [:admin, @advertiser, @campaign], html: { class: 'needs-validation', novalidate: '' } do |f| %>
  <div class="mb-3">
    <%= f.label :name, class: 'form-label' %>
    <%= f.text_field :name, class: 'form-control', required: true %>
  </div>
  
  <div class="mb-3">
    <%= f.label :description, class: 'form-label' %>
    <%= f.text_area :description, class: 'form-control', rows: 3, required: true %>
  </div>
  
  <div class="mb-3">
    <%= f.label :budget, class: 'form-label' %>
    <%= f.number_field :budget, class: 'form-control', required: true %>
  </div>
  
  <div class="mb-3">
    <%= f.label :start_date, class: 'form-label' %>
    <%= f.date_select :start_date, { discard_year: false, order: [:day, :month, :year] }, class: 'form-control', required: true %>
  </div>

  <div class="mb-3">
    <%= f.label :end_date, class: 'form-label' %>
    <%= f.date_select :end_date, { discard_year: false, order: [:day, :month, :year] }, class: 'form-control', required: true %>
  </div>

  <div class="mb-3">
    <%= f.label :status, class: 'form-label' %>
    <%= f.select :status, Campaign.statuses.keys, {}, class: 'form-select', required: true %>
  </div>

  <div class="mb-3">
    <%= f.label :advertiser_id, class: 'form-label' %>
    <%= f.hidden_field :advertiser_id, value: @advertiser.id %>
  </div>
  
  <%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

web/app/views/admin/campaigns/edit.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Edit Campaign for <%= @advertiser.name %></h1>
  
  <%= render 'campaign_form', campaign: @campaign, advertiser: @advertiser %>
  
  <%= link_to 'Back to Campaign List', admin_advertiser_campaigns_path(@advertiser), class: "btn btn-secondary mt-3" %>
</div>

web/app/views/admin/campaigns/index.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Manage Campaigns for <%= @advertiser.name %></h1>

  <table class="table table-striped table-bordered">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Description</th>
        <th scope="col">Budget</th>
        <th scope="col">Start Date</th>
        <th scope="col">End Date</th>
        <th scope="col">Status</th>
        <th scope="col">Advertiser</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @campaigns.each do |campaign| %>
        <tr>
          <td><%= campaign.name %></td>
          <td><%= campaign.description %></td>
          <td><%= campaign.budget %></td>
          <td><%= campaign.start_date %></td>
          <td><%= campaign.end_date %></td>
          <td><%= campaign.status %></td>
          <td>
            <%= link_to campaign.advertiser.name, admin_advertiser_campaigns_path(campaign.advertiser) %>
          </td>
          <td>
            <%= link_to 'Edit', edit_admin_advertiser_campaign_path(campaign.advertiser, campaign), class: "btn btn-primary btn-sm" %>
            <%= link_to 'Delete', admin_advertiser_campaign_path(campaign.advertiser, campaign), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
            <%= link_to 'View Adverts', admin_advertiser_campaign_adverts_path(campaign.advertiser, campaign), class: "btn btn-info btn-sm" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'Add New Campaign', new_admin_advertiser_campaign_path, class: "btn btn-success" %>

<%= link_to 'Back to Advertisers', admin_advertisers_path, class: 'btn btn-secondary' %>

</div>

web/app/views/admin/campaigns/new.html.erb
<h1>Create New Campaign</h1>

<%= render 'campaign_form' %>