web/config/routes.rb
Rails.application.routes.draw do

  resources :articles do
    resources :comments, only: [:create, :edit, :update, :destroy] do
      resources :replies, only: [:create, :destroy]  
    end

    member do
      post :flag

      # Pinning
      post :pin
      post :unpin
    end  
  end

  resources :companies, path: 'c' do
    resources :comments, only: [:create, :edit, :update, :destroy] do
      resources :replies, only: [:create, :destroy]  
    end


    member do
      post :pin
      post :unpin
    end
  end

  resources :listings do
    resources :comments, only: [:create, :edit, :update, :destroy] do
      resources :replies, only: [:create, :destroy]  
    end

    member do
      post :flag
      post :pin
      post :unpin
    end
  end

  resources :jobs do
    resources :comments, only: [:create, :edit, :update, :destroy] do
      resources :replies, only: [:create, :destroy]  
    end

    member do
      post :flag

      # Pinning
      post :pin
      post :unpin
    end  
  end

  resources :comments, only: [] do  
    resources :replies, only: [:create, :destroy], as: 'replies' do
      member do
        post :flag
      end
    end
    
    member do
      post :flag
    end
  end


  # User Poasts

  resources :poasts do
    resources :comments, only: [:create, :edit, :update, :destroy] do
      resources :replies, only: [:create, :destroy]  
    end

    member do
      post :flag
      post :pin
      delete :unpin
    end
  end

  # Direct Messages
  
  resources :conversations, only: [:index, :new, :show, :create] do
    resources :messages, only: [:create]
  end

  # config/routes.rb
  post 'start_conversation/:recipient_id', to: 'conversations#start_conversation', as: 'start_conversation'



  # Notifications 
  resources :notifications, only: [:index] do
    member do
      post :mark_as_read
    end
    collection do
      post :mark_all_as_read
    end
  end

  # Following/Followers
  resources :relationships, only: [:create, :destroy]


  # Timeline

  get '/timeline', to: 'timelines#show', as: :timeline

  #resources :timelines, only: [:show]

  # Moderator Dashboard
  resources :moderators, only: [:index] do
    collection do
      post :hide_item, as: 'hide_item'
      post :unflag_item, as: 'unflag_item'
      post :lock_user
      post :unlock_user

      # Find and assign/remove badges to users
      post :assign_badge  
      delete :remove_badge 
      get :search_user, as: 'search_user'

      # Create new types of badges
      get :new_badge, as: 'new_badge'
      post :create_badge, as: 'create_badge'

      # Create global alert messages
      get :new_alert
      post :create_alert
      post :remove_alert
    end
  end
  
  # Admin Dashboard
  namespace :admin do
    root to: 'admin#index'  
    resources :advertisers, only: [:index, :new, :create, :edit, :update, :destroy] do
      resources :campaigns, only: [:index, :new, :create, :edit, :update, :destroy] do
        resources :adverts, only: [:index, :new, :create, :edit, :update, :destroy]
      end
    end
  end
  
  # for user IP storage, custom sessions & reg controller
devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
}
  resources :users, only: [:show] do
    resources :poasts, only: [:index]
    
    resources :comments, only: [:create, :edit, :update, :destroy] do
      resources :replies, only: [:create, :destroy]  
    end

    member do
      
      get 'comments'
      get 'listings'
      get 'articles'
      
      get 'edit_bio'
      patch 'update_bio'
      
      post 'flag'
      post 'lock'  

      get 'followers'
      get 'following'

      
    end
  end


  # Search users
  get 'search_users', to: 'users#search'



  # Landing page
  root 'home#index'

  get '/marketplace', to: 'listings#index', as: 'marketplace'
  get '/privacy-policy', to: 'home#privacy_policy'
  get '/terms-of-service', to: 'home#terms_of_service'
  get '/new-user-guide', to: 'home#new_user_guide'
  
  
end

web/app/models/notification.rb
class Notification < ApplicationRecord
    belongs_to :user
    belongs_to :notifiable, polymorphic: true
  
    enum status: { unread: 0, read: 1 }

    validates :user_id, :notifiable_type, :notifiable_id, :status, presence: true
    #validates :status, inclusion: { in: [0, 1] }
    #validates :status, inclusion: { in: statuses.keys } # If using enum for status
  
    # Custom validation for notifiable_type to ensure it's a valid type
    validate :validate_notifiable_type
  
    private
  
    def validate_notifiable_type
      valid_types = ['Comment', 'Poast', 'Message', 'Reply', 'Job', "Relationship", 'Listing', 'Article'] 
      unless valid_types.include?(notifiable_type)
        errors.add(:notifiable_type, 'is not a valid notifiable type')
      end
    end


end
  

web/app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
    before_action :authenticate_user!
  
    def index
        @notifications = current_user.notifications.unread.order(created_at: :desc).page(params[:page]).per(10)
    end
    
  
    # Mark a notification as read      
    def mark_as_read
        @notification = Notification.find(params[:id])

        if @notification.user == current_user
            @notification.update!(status: :read)

            respond_to do |format|
            format.turbo_stream
            end
        else
            redirect_to root_path, alert: 'You do not have permission to access this resource.'
        end
    end
  
    def mark_all_as_read
        current_user.notifications.unread.update_all(status: :read)
        redirect_to notifications_path, notice: 'All notifications have been marked as read.'
    end
end
  

web/app/views/notifications/_mark_all_as_read.html.erb
<%= form_with(url: mark_all_as_read_notifications_path, method: :post) do |f| %>
  <%= f.submit 'Mark All As Read', class: 'btn btn-primary' %>
<% end %>

web/app/views/notifications/index.html.erb
<div class="container mt-5 mb-5">
  <% content_for :page_title do %>
    Notifications
  <% end %>

  <% if @notifications.any? %>
    <%= render 'mark_all_as_read' %>
  <% end %>

  <% if @notifications.empty? %>
    <div class="text-center mt-4">
      <h5 class="text-muted">You have no new notifications at the moment.</h5>
      <p>Stay tuned! Notifications about your interactions and updates will appear here.</p>
    </div>
  <% else %>
    <div class="list-group mt-4">
      <% @notifications.each do |notification| %>
        <div class="list-group-item" id="notification_<%= notification.id %>">
          <div class="d-flex justify-content-between align-items-center">
            <h5 class="mb-0 me-2">
              <% notifiable = notification.notifiable %>
              <% case notifiable.class.name %>
              <% when 'Comment' %>
                <%= link_to notification.message, polymorphic_path(notifiable.commentable, anchor: "comment_#{notifiable.id}") %>
              <% when 'Reply' %>
                <% comment = notifiable.comment %>
                <% commentable = comment.commentable %>
                <%= link_to notification.message, polymorphic_path(commentable, anchor: "reply_#{notifiable.id}") %>
              <% when 'Message' %>
                <%= link_to notification.message, conversation_path(notifiable.conversation_id, anchor: "message_#{notifiable.id}") %>
              <% when 'Relationship' %>
                <% if notifiable.follower.present? %>
                  <%= link_to notification.message, user_path(notifiable.follower.username) %>
                <% else %>
                  <%= notification.message %>
                <% end %>
              <% when 'Poast' %>
                <%= link_to notification.message, poast_path(notifiable.id, anchor: "poast_#{notifiable.id}") %>
              <% when 'Listing' %>
                <%= link_to notification.message, listing_path(notifiable.id, anchor: "listing_#{notifiable.id}") %>
              <% when 'Job' %>
                <%= link_to notification.message, job_path(notifiable.id, anchor: "job_#{notifiable.id}") %>
              <% when 'Article' %>
                <%= link_to notification.message, article_path(notifiable.id, anchor: "article_#{notifiable.id}") %>
              <% else %>
                <%= notification.message %>
              <% end %>
            </h5>
            <small class="text-muted me-2">Received at <%= notification.created_at.strftime('%Y-%m-%d %H:%M:%S') %></small>
            <%= form_with url: mark_as_read_notification_path(notification), method: :post, data: { turbo_frame: "notification_#{notification.id}" }, class: 'mb-0' do %>
              <%= submit_tag 'Mark as Read', class: 'btn btn-sm btn-primary mb-0' %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="mt-4">
      <%= paginate @notifications %>
    </div>
  <% end %>
</div>

web/app/views/notifications/mark_as_read.turbo_stream.erb
<turbo-stream action="replace" target="notification_<%= @notification.id %>">
  <template>
    <!-- Your updated notification markup here -->
    <li id="notification_<%= @notification.id %>">
      <!-- ... -->
      <small>Marked as read</small>
    </li>
  </template>
</turbo-stream>